### ISSUE TITLE
No Supabase?

### ISSUE THREAD

**Issue by kungfu-eric** [pChitral/ETL-SEC-EDGAR-10-k-Filings#4]
Your original goal of integration with Supabase is very useful. What happened?

**Comment by pChitral** [comment]
The project initially aimed to integrate Supabase to track word counts from an annotated list, assessing their predictive value for our model. However, we shifted focus to storing entire texts from 10k reports, which wasn't feasible with Supabase due to cost concerns. Therefore, we suspended the Supabase integration, although you can still find it in an archived repository.

**Comment by kungfu-eric** [comment]
Thanks
